<script src="AdminFunc.js" type="text/javascript"></script>
<script src="QTypeControl.js" type=text/javascript></script>
<title>ILOsys v2 Beta</title>
</head>

<body link="#333399" vlink="#333399" alink="#333399" bgcolor="#666666" onLoad="setStart()">
<br><br><br>
<table align="center" border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="500" id="AutoNumber1" bgcolor="#FFFFFF">
  <tr>
    <td width="100%">
    <p align="right"><font size="1" face="Arial">
    <a href="admin.php">Admin Menu</a>
    &nbsp;|&nbsp;
    <a href="../index.html">Home</a>
    &nbsp;&nbsp;&nbsp;&nbsp;
    </font>
    </td>
  </tr>
  <tr>
    <td width="100%">
    <br>
    <table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="95%" id="AutoNumber2">
      <tr>
        <td width="100%">
        <font size="2" face="arial">